blank_issues_enabled: true
contact_links:
  - name: â“ Question - Ask us
    url: mailto:imptodefeat@gmail.com
    about: This issue tracker is not for technical support. Please use one of our dedicated channels, and ask the community for help.
